title: Calcupedia Backup
theme: just-the-docs
color_scheme: dark
markdown: kramdown

logo: "/assets/images/logo.png"

kramdown:
  math_engine: mathjax

aux_links:
  "GitHub repository": "//github.com/fxesdev/calcupedia_backup"

nav_external_links:
  - title: Go to the real Calcupedia
    url: https://gwe.42web.io/calcupedia

nav_sort: case_insensitive

search:
    rel_url: true

callouts:
    warning:
        title: Warning
        color: red
    hatnote:
        color: purple
